// vue/src/App.vue
<template>
    <DxTreeView
      id="simple-treeview"
      :data-source=products
      dataStructure="plain"
      keyExpr="ID"
      displayExpr="name"
      parentIdExpr="categoryId"
      :search-enabled="true"
      selectionMode="single"
      :select-by-click="true"
      :on-item-click="selectProduct" 
    />

    <div id="product-details" v-if="currentProduct.price">
      <img :src="currentProduct.image" >
      <div class="name">{{ currentProduct.name }}</div>
      <div class="price">${{ currentProduct.price }}</div> 
    </div>

</template>

<script>
import DxTreeView from 'devextreme-vue/tree-view';
import products from './products';

export default {
  name: 'App',
  components: {
    DxTreeView
  },
  data() {
    return {
      products: products,
      currentProduct: products[0],
    }
  },
  methods: {
    selectProduct(e) {
      this.currentProduct = e.itemData;
    }
  }
}
</script>

<style>
#simple-treeview, #product-details {
    display: inline-block;
    width: 300px;
}

#product-details {
    vertical-align: top;
    width: 400px;
    height: 420px;
    margin-left: 20px;
}

#product-details > img {
    border: none;
    height: 300px;
    width: 400px;
}

#product-details > .name {
    text-align: center;
    font-size: 20px;
}

#product-details > .price {
    text-align: center;
    font-size: 24px;
}
</style>

// react/src/App.js
import React, { useState } from 'react';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import TreeView from 'devextreme-react/tree-view';
import products from './products';

function App() {
  const [selectedNode, setSelectedNode] = useState(products[0]);
  const selectProduct = (e) => {
    setSelectedNode(e.itemData);
  }

  const itemTemplate = (item) => {
    if (item.price) {
      return `<div> ${item.name} ($${item.price}) </div>`;
    } else {
      return `<div> ${item.name} </div>`;
    }
  }

  return (
    <div className="App">
      <TreeView 
        id="simple-treeview"
        dataSource={products}
        dataStructure="plain"
        keyExpr="ID"
        displayExpr="name"
        parentIdExpr="categoryId"
        itemTemplate={itemTemplate}
        searchEnabled={true}
        selectionMode="single"
        selectByClick={true}
        onItemClick={selectProduct}
      />

      {
        selectedNode.price &&
        <div id="product-details">
          <img src={selectedNode.image}/>
          <div className="name">{selectedNode.name}</div>
          <div className="price">{`$${ selectedNode.price}`}</div>
        </div>
      }
    </div>
  );
}

export default App;
