// angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { Product, AppService } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  products: Product[];
  currentProduct: Product;

  constructor(service: AppService) {
      this.products = service.getProducts();
      this.currentProduct = this.products[0];
  }

  selectProduct(e) {
      this.currentProduct = e.itemData;
  }
}

<dx-tree-view
  id="simple-treeview"
  [dataSource]="products"
  dataStructure="plain"
  keyExpr="ID"
  displayExpr="name"
  parentIdExpr="categoryId"
  itemTemplate="productTemplate"
  searchEnabled=true
  selectionMode="single"
  selectByClick=true
  (onItemClick)="selectProduct($event)"
>
  <div *dxTemplate="let product of 'productTemplate'">
    {{ product.price ? product.name + "(" + product.price + ")" : product.name }}
  </div>
</dx-tree-view>
<div id="product-details" *ngIf="currentProduct.price">
    <img [src]="currentProduct.image" />
    <div class="name">{{currentProduct.name}}</div>
    <div class="price">${{ currentProduct.price }}</div>
</div>

// react/src/App.js
import React, { useState } from 'react';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';
import './App.css'

import TreeView from 'devextreme-react/tree-view';
import products from './products';

function App() {
  const [selectedNode, setSelectedNode] = useState(products[0]);
  const selectProduct = (e) => {
    setSelectedNode(e.itemData);
  }

  const itemTemplate = (item) => {
    if (item.price) {
      return `<div> ${item.name} ($${item.price}) </div>`;
    } else {
      return `<div> ${item.name} </div>`;
    }
  }

  return (
    <div className="App">
      <TreeView 
        id="simple-treeview"
        dataSource={products}
        dataStructure="plain"
        keyExpr="ID"
        displayExpr="name"
        parentIdExpr="categoryId"
        itemTemplate={itemTemplate}
        searchEnabled={true}
        selectionMode="single"
        selectByClick={true}
        onItemClick={selectProduct}
      />

      {
        selectedNode.price &&
        <div id="product-details">
          <img src={selectedNode.image}/>
          <div className="name">{selectedNode.name}</div>
          <div className="price">{`$${ selectedNode.price}`}</div>
        </div>
      }
    </div>
  );
}

export default App;
